# Generated by Django 6.1.1 on 2026-09-03 09:30

import django.db.models.deletion
import pengajuan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Kode Pengajuan')),
                ('kategori', models.CharField(blank=True, choices=[('Ibadah', 'Ibadah'), ('Pendidikan', 'Pendidikan'), ('Keperluan Pribadi', 'Keperluan Pribadi'), ('Lainnya', 'Lainnya')], max_length=30)),
                ('maksud', models.TextField(blank=True, verbose_name='Maksud Perjalanan')),
                ('tujuan_negara', models.CharField(blank=True, max_length=100)),
                ('sumber_pembiayaan', models.CharField(blank=True, choices=[('Biaya Sendiri', 'Biaya Sendiri'), ('Sponsor/Penyelenggara', 'Sponsor/Penyelenggara'), ('Negara/Lembaga Lain', 'Negara/Lembaga Lain')], max_length=30)),
                ('tgl_berangkat', models.DateField(blank=True, null=True)),
                ('tgl_kembali', models.DateField(blank=True, null=True)),
                ('jumlah_hari_kerja', models.PositiveIntegerField(blank=True, null=True)),
                ('kanal', models.CharField(choices=[('mobile', 'Mobile App'), ('web', 'Web App')], default='web', max_length=10)),
                ('status', models.CharField(choices=[('belum', 'Belum Diajukan'), ('proses', 'Dalam Proses Unor'), ('proses_pakln', 'Dalam Proses Biro PAKLN'), ('selesai', 'Selesai')], default='belum', max_length=20)),
                ('form_saved', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('preview_unor_agree', models.BooleanField(default=False)),
                ('preview_pakln_agree', models.BooleanField(default=False)),
                ('tgl_pengajuan', models.DateField(blank=True, null=True)),
                ('tgl_masuk_pakln', models.DateField(blank=True, null=True)),
                ('tgl_selesai', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengajuan',
                'verbose_name_plural': 'Pengajuan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DokumenUnor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('nd_sekunor', 'Nota Dinas Sekretaris Unor'), ('iln_pimpinan', 'Formulir Izin Luar Negeri (TTD Pimpinan Unor)'), ('nd_menteri', 'Nota Dinas Permohonan Persetujuan Menteri'), ('disposisi', 'Lembar Disposisi'), ('nd_biropakln', 'Nota Dinas ke Biro PAKLN')], max_length=20)),
                ('file', models.FileField(upload_to=pengajuan.models.dokumen_unor_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_unor', to='pengajuan.pengajuan')),
            ],
            options={
                'verbose_name': 'Dokumen Administrasi Unor',
                'verbose_name_plural': 'Dokumen Administrasi Unor',
                'unique_together': {('pengajuan', 'jenis')},
            },
        ),
        migrations.CreateModel(
            name='DokumenPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('cuti', 'Formulir Persetujuan Cuti Pegawai'), ('iln', 'Formulir Izin Luar Negeri'), ('pendukung', 'Dokumen Pendukung'), ('notadinas', 'Nota Dinas Pimpinan Unit Kerja ke Sekretaris Unor')], max_length=20)),
                ('file', models.FileField(upload_to=pengajuan.models.dokumen_pegawai_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_pegawai', to='pengajuan.pengajuan')),
            ],
            options={
                'verbose_name': 'Dokumen Pegawai',
                'verbose_name_plural': 'Dokumen Pegawai',
                'unique_together': {('pengajuan', 'jenis')},
            },
        ),
        migrations.CreateModel(
            name='DokumenPakln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('nd_kabag', 'Nota Dinas Kepala Bagian'), ('nd_kabiro', 'Nota Dinas Kepala Biro'), ('iln_sekjen', 'Izin Luar Negeri (TTD Sekjen a.n. Menteri)')], max_length=20)),
                ('file', models.FileField(upload_to=pengajuan.models.dokumen_pakln_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_pakln', to='pengajuan.pengajuan')),
            ],
            options={
                'verbose_name': 'Dokumen Administrasi Biro PAKLN',
                'verbose_name_plural': 'Dokumen Administrasi Biro PAKLN',
                'unique_together': {('pengajuan', 'jenis')},
            },
        ),
    ]
