# Generated by Django 6.1.1 on 2026-09-23 05:37

import django.db.models.deletion
import pengajuan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paspor', '0003_sumberpembiayaan'),
        ('pengajuan', '0007_pengajuan_sumber_pembiayaan_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanND',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan_plt_kabag_kln', models.CharField(default='Plt. Kepala Bagian Kerja Sama Luar Negeri', help_text='Diisi pada baris "Dari:" Nota Dinas Kabag KLN ke Karo PAKLN.', max_length=150, verbose_name='Jabatan Plt. Kepala Bagian KLN')),
                ('nama_pejabat_plt_kabag_kln', models.CharField(blank=True, help_text='Nama pejabat yang menandatangani sebagai Plt. Kepala Bagian KLN.', max_length=150, verbose_name='Nama Pejabat Plt. Kepala Bagian KLN')),
                ('paraf_ketua_tim_aki', models.CharField(default='Ketua Tim AKI', max_length=150, verbose_name='Kotak Paraf — Ketua Tim AKI (ND Kabag KLN)')),
                ('nama_karo_pakln', models.CharField(default='Reiza Setiawan', help_text='Penandatangan Nota Dinas Karo PAKLN ke Sekretaris Jenderal.', max_length=150, verbose_name='Nama Kepala Biro PAKLN')),
                ('paraf_katim_aki_nd2', models.CharField(default='Katim AKI', max_length=150, verbose_name='Kotak Paraf 1 — Katim AKI (ND Karo PAKLN)')),
                ('paraf_plt_kabag_kln_nd2', models.CharField(default='Plt. Kabag KLN', max_length=150, verbose_name='Kotak Paraf 2 — Plt. Kabag KLN (ND Karo PAKLN)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Nota Dinas',
                'verbose_name_plural': 'Pengaturan Nota Dinas',
            },
        ),
        migrations.CreateModel(
            name='NotaDinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maksud', models.TextField(verbose_name='Maksud Perjalanan')),
                ('nama_ringkas', models.CharField(help_text="Nama pegawai pertama + 'dkk' bila lebih dari satu pegawai.", max_length=150, verbose_name='Nama (a.n.)')),
                ('file', models.FileField(upload_to=pengajuan.models.nota_dinas_path, verbose_name='Berkas PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('negara_tujuan', models.ManyToManyField(related_name='+', to='paspor.negara', verbose_name='Tujuan Negara')),
                ('pengajuan_list', models.ManyToManyField(related_name='nota_dinas_list', to='pengajuan.pengajuan', verbose_name='Pengajuan')),
                ('unit_organisasi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='paspor.unitorganisasi', verbose_name='Unit Organisasi')),
            ],
            options={
                'verbose_name': 'Riwayat Generate ND',
                'verbose_name_plural': 'Riwayat Generate ND',
                'ordering': ['-created_at'],
            },
        ),
    ]
