# Generated by Django 6.1.1 on 2026-09-23 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0008_kategori_perjalanan_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengajuan',
            name='catatan_pakln',
            field=models.TextField(blank=True, verbose_name='Catatan Admin PKLN'),
        ),
    ]
