# Generated by Django 6.1.1 on 2026-09-24 02:38
#
# "Dokumen lainnya" (Nota Dinas Kepala Bagian/Kepala Biro) pindah dari 2
# unggahan wajib terpisah (DokumenPakln) menjadi 1 berkas pendukung opsional
# + checklist (DokumenPaklnPendukung), meniru pola DokumenUnorPendukung.
#
# Data lama dipertahankan: baris DokumenPakln dengan jenis nd_kabag/
# nd_kabiro yang mungkin sudah ada dikonsolidasikan ke
# DokumenPaklnPendukung (berkas pertama yang ditemukan dipakai sebagai
# berkas pendukung, checklist kedua jenis dicentang sesuai baris yang ada),
# baru baris lama dihapus.

import django.db.models.deletion
import pengajuan.models
from django.db import migrations, models
from django.utils import timezone


def migrate_pendukung_forward(apps, schema_editor):
    DokumenPakln = apps.get_model("pengajuan", "DokumenPakln")
    DokumenPaklnPendukung = apps.get_model("pengajuan", "DokumenPaklnPendukung")

    legacy = DokumenPakln.objects.filter(jenis__in=["nd_kabag", "nd_kabiro"])
    for pengajuan_id in legacy.values_list("pengajuan_id", flat=True).distinct():
        rows = list(legacy.filter(pengajuan_id=pengajuan_id))
        pendukung, _ = DokumenPaklnPendukung.objects.get_or_create(pengajuan_id=pengajuan_id)
        for row in rows:
            if row.jenis == "nd_kabag":
                pendukung.nd_kabag = True
            elif row.jenis == "nd_kabiro":
                pendukung.nd_kabiro = True
            if not pendukung.file:
                pendukung.file = row.file
                pendukung.uploaded_at = row.uploaded_at or timezone.now()
        pendukung.save()
    legacy.delete()


def migrate_pendukung_backward(apps, schema_editor):
    # Tidak dapat memulihkan 2 berkas terpisah dari 1 berkas gabungan —
    # cukup no-op (data pendukung akan hilang jika migrasi ini di-revert).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0009_pengajuan_catatan_pakln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenpakln',
            name='jenis',
            field=models.CharField(choices=[('iln_sekjen', 'Izin Luar Negeri (TTD Sekjen a.n. Menteri)')], max_length=20),
        ),
        migrations.CreateModel(
            name='DokumenPaklnPendukung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=pengajuan.models.dokumen_pakln_pendukung_path)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('nd_kabag', models.BooleanField(default=False, verbose_name='Nota Dinas Kepala Bagian')),
                ('nd_kabiro', models.BooleanField(default=False, verbose_name='Nota Dinas Kepala Biro')),
                ('pengajuan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_pakln_pendukung', to='pengajuan.pengajuan')),
            ],
            options={
                'verbose_name': 'Dokumen Pendukung Biro PAKLN',
                'verbose_name_plural': 'Dokumen Pendukung Biro PAKLN',
            },
        ),
        migrations.RunPython(migrate_pendukung_forward, migrate_pendukung_backward),
    ]
