# Generated by Django 6.1.1 on 2026-09-25 01:43

import django.db.models.deletion
import pengajuan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0010_alter_dokumenpakln_jenis_dokumenpaklnpendukung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenGenerateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('nd_kabag', 'ND Kabag'), ('nd_karo', 'ND Karo')], max_length=20)),
                ('jumlah_pengajuan', models.PositiveIntegerField(default=1, help_text='Jumlah pengajuan yang diproses dalam satu batch generate ini.', verbose_name='Jumlah Pengajuan')),
                ('file', models.FileField(upload_to=pengajuan.models.dokumen_generate_log_path, verbose_name='Berkas PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ManyToManyField(blank=True, related_name='dokumen_generate_logs', to='pengajuan.pengajuan', verbose_name='Pengajuan Terkait')),
            ],
            options={
                'verbose_name': 'Riwayat Generate Dokumen',
                'verbose_name_plural': 'Riwayat Generate Dokumen',
                'ordering': ['-created_at'],
            },
        ),
    ]
