# Generated by Django 6.1.1 on 2026-09-29 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0011_dokumengeneratelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanDokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan_penandatangan', models.CharField(blank=True, max_length=150, verbose_name='Jabatan Pejabat Penandatangan')),
                ('nama_pejabat', models.CharField(blank=True, max_length=150, verbose_name='Nama Pejabat')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pengaturan Dokumen',
                'verbose_name_plural': 'Pengaturan Dokumen',
            },
        ),
    ]
