# Generated by Django 6.1.1 on 2026-09-30 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0013_pengaturandokumen_kabag_karo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatPengajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aksi', models.CharField(choices=[('dikirim', 'Diajukan ke Admin Unor'), ('dikirim_ulang', 'Perbaikan dikirim ke Admin Unor'), ('dikembalikan_unor', 'Dikembalikan Admin Unor ke Pegawai'), ('diteruskan_pakln', 'Diteruskan ke Biro PAKLN'), ('dikembalikan_pakln', 'Dikembalikan Biro PAKLN ke Admin Unor'), ('selesai', 'Selesai diproses')], max_length=30)),
                ('status_dari', models.CharField(choices=[('belum', 'Belum Diajukan'), ('proses', 'Dalam Proses Unor'), ('proses_pakln', 'Dalam Proses Biro PAKLN'), ('selesai', 'Selesai')], max_length=20)),
                ('status_ke', models.CharField(choices=[('belum', 'Belum Diajukan'), ('proses', 'Dalam Proses Unor'), ('proses_pakln', 'Dalam Proses Biro PAKLN'), ('selesai', 'Selesai')], max_length=20)),
                ('aktor_role', models.CharField(max_length=20)),
                ('aktor_nama', models.CharField(max_length=150)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aktor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riwayat_pengajuan', to=settings.AUTH_USER_MODEL)),
                ('pengajuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='pengajuan.pengajuan')),
            ],
            options={
                'verbose_name': 'Riwayat Pengajuan',
                'verbose_name_plural': 'Riwayat Pengajuan',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['pengajuan', 'created_at'], name='pengajuan_r_pengaju_5f92cc_idx')],
            },
        ),
    ]
