# Generated by Django 6.1.1 on 2026-10-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0013_pengaturandokumen_kabag_karo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenpakln',
            name='jenis',
            field=models.CharField(choices=[('iln_sekjen', '3.a Izin Luar Negeri (TTD Sekjen a.n. Menteri)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dokumenpegawai',
            name='jenis',
            field=models.CharField(choices=[('cuti', '1.a Formulir Persetujuan Cuti Pegawai'), ('iln', '1.b Formulir Izin Luar Negeri'), ('notadinas', '1.c Nota Dinas Pimpinan Unit Kerja ke Sekretaris Unor'), ('pendukung', '1.d Dokumen Pendukung')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dokumenunor',
            name='jenis',
            field=models.CharField(choices=[('disposisi', '2.a Lembar Disposisi / Izin Prinsip'), ('iln_pimpinan', '2.b Formulir Izin Luar Negeri (TTD Pimpinan Unor)'), ('nd_biropakln', '2.c Nota Dinas Sekertaris Unor ke Biro PAKLN')], max_length=20),
        ),
    ]
