# Generated by Django 6.1.1 on 2026-10-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0014_alter_dokumenpakln_jenis_alter_dokumenpegawai_jenis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenpakln',
            name='tanggal_surat',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Surat'),
        ),
        migrations.AddField(
            model_name='dokumenpegawai',
            name='tanggal_surat',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Surat'),
        ),
        migrations.AddField(
            model_name='dokumenunor',
            name='tanggal_surat',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Surat'),
        ),
    ]
