# Generated by Django 6.1.1 on 2026-10-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengajuan', '0016_merge_riwayat_dan_tanggal_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayatpengajuan',
            name='aksi',
            field=models.CharField(choices=[('dikirim', 'Diajukan ke Admin Unor'), ('dikirim_ulang', 'Perbaikan dikirim ke Admin Unor'), ('dikembalikan_unor', 'Dikembalikan Admin Unor ke Pegawai'), ('diteruskan_pakln', 'Diteruskan ke Biro PAKLN'), ('dikembalikan_pakln', 'Dikembalikan Biro PAKLN ke Admin Unor'), ('diteruskan_ulang', 'Perbaikan diteruskan ke Biro PAKLN'), ('selesai', 'Selesai diproses')], max_length=30),
        ),
    ]
