# Generated by Django 6.1.1 on 2026-10-05 06:32

import django.db.models.deletion
import django.utils.timezone
import pengajuan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paspor', '0006_pdln_master'),
        ('pengajuan', '0017_riwayat_diteruskan_ulang'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailPdln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penyelenggara', models.CharField(blank=True, max_length=200, verbose_name='Penyelenggara')),
                ('perguruan_tinggi', models.CharField(blank=True, max_length=200, verbose_name='Perguruan Tinggi')),
                ('kota_tujuan', models.CharField(blank=True, max_length=150, verbose_name='Kota Tujuan')),
                ('tgl_mulai_kegiatan', models.DateField(blank=True, null=True, verbose_name='Tanggal Mulai Kegiatan')),
                ('tgl_selesai_kegiatan', models.DateField(blank=True, null=True, verbose_name='Tanggal Selesai Kegiatan')),
                ('beasiswa_pintar_id', models.CharField(blank=True, max_length=50, verbose_name='ID Pencalonan PINTAR')),
                ('beasiswa_nama', models.CharField(blank=True, max_length=255, verbose_name='Nama Beasiswa')),
                ('pernyataan_benar', models.BooleanField(default=False, verbose_name='Pernyataan kebenaran data')),
            ],
            options={
                'verbose_name': 'Detail PDLN',
                'verbose_name_plural': 'Detail PDLN',
            },
        ),
        migrations.CreateModel(
            name='DokumenBpsdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('izin_prinsip', 'Izin Prinsip Menteri'), ('ikatan_dinas_ttd', 'Perjanjian Ikatan Dinas ttd full / SK Tugas Belajar'), ('nd_kabiro_pakln', 'Nota Dinas Sekretaris BPSDM ke Kepala Biro PAKLN')], max_length=30)),
                ('file', models.FileField(upload_to=pengajuan.models.dokumen_bpsdm_path)),
                ('tanggal_surat', models.DateField(blank=True, null=True, verbose_name='Tanggal Surat')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dokumen Administrasi BPSDM',
                'verbose_name_plural': 'Dokumen Administrasi BPSDM',
            },
        ),
        migrations.CreateModel(
            name='LaporanPdln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=pengajuan.models.laporan_pdln_path, verbose_name='Berkas Laporan')),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('dikembalikan', 'Dikembalikan'), ('disetujui', 'Disetujui')], db_index=True, default='menunggu', max_length=20)),
                ('catatan_pakln', models.TextField(blank=True, verbose_name='Catatan Admin PAKLN')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tgl_disetujui', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Laporan PDLN',
                'verbose_name_plural': 'Laporan PDLN',
            },
        ),
        migrations.CreateModel(
            name='PermohonanPembatalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diajukan_role', models.CharField(max_length=20)),
                ('alasan', models.TextField(verbose_name='Alasan Pembatalan')),
                ('status', models.CharField(choices=[('menunggu_unor', 'Menunggu Admin Unor'), ('menunggu_pakln', 'Menunggu Biro PAKLN'), ('disetujui', 'Disetujui'), ('ditolak', 'Ditolak'), ('ditarik', 'Ditarik')], db_index=True, max_length=20)),
                ('status_pengajuan_saat_diajukan', models.CharField(choices=[('belum', 'Belum Diajukan'), ('proses', 'Dalam Proses Unor'), ('proses_bpsdm', 'Dalam Proses BPSDM'), ('proses_pakln', 'Dalam Proses Biro PAKLN'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], max_length=20)),
                ('unor_waktu', models.DateTimeField(blank=True, null=True)),
                ('unor_catatan', models.TextField(blank=True)),
                ('pakln_waktu', models.DateTimeField(blank=True, null=True)),
                ('pakln_catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permohonan Pembatalan',
                'verbose_name_plural': 'Permohonan Pembatalan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dokumentemplate',
            name='jenis_perjalanan',
            field=models.CharField(blank=True, choices=[('nondinas', 'Non-Kedinasan'), ('pdln', 'PDLN')], help_text='Kosongkan agar berlaku untuk Non-Kedinasan maupun PDLN.', max_length=20, verbose_name='Jenis Perjalanan Tertentu'),
        ),
        migrations.AddField(
            model_name='dokumentemplate',
            name='untuk_admin_bpsdm',
            field=models.BooleanField(default=False, verbose_name='Untuk Admin BPSDM'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='catatan_bpsdm',
            field=models.TextField(blank=True, verbose_name='Catatan Admin BPSDM'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='jenis_perjalanan',
            field=models.CharField(choices=[('nondinas', 'Non-Kedinasan'), ('pdln', 'PDLN')], default='nondinas', max_length=20, verbose_name='Jenis Perjalanan'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='preview_bpsdm_agree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='tgl_dibatalkan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='tgl_masuk_bpsdm',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='tipe_pdln',
            field=models.CharField(blank=True, choices=[('T1', 'PDLN Tipe 1'), ('T2P', 'PDLN Tipe 2 — Pendidikan'), ('T2L', 'PDLN Tipe 2 — Pelatihan'), ('T3', 'PDLN Tipe 3 — Penugasan Khusus')], max_length=5, verbose_name='Tipe PDLN'),
        ),
        migrations.AddField(
            model_name='pengajuan',
            name='unit_organisasi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='paspor.unitorganisasi', verbose_name='Unit Organisasi (saat diajukan)'),
        ),
        migrations.AlterField(
            model_name='dokumenpakln',
            name='jenis',
            field=models.CharField(choices=[('iln_sekjen', '3.a Izin Luar Negeri (TTD Sekjen a.n. Menteri)'), ('sp_setneg', 'SP Setneg'), ('paspor_dinas', 'Paspor Dinas'), ('exit_permit', 'Exit Permit'), ('visa', 'Rekomendasi Visa'), ('sk_tubel', 'SK Tugas Belajar'), ('nd_karo_unor', 'Nota Dinas Karo PAKLN ke Sekretaris Unor hal Penyampaian Dokumen PDLN')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dokumenpegawai',
            name='jenis',
            field=models.CharField(choices=[('cuti', '1.a Formulir Persetujuan Cuti Pegawai'), ('iln', '1.b Formulir Izin Luar Negeri'), ('notadinas', '1.c Nota Dinas Pimpinan Unit Kerja ke Sekretaris Unor'), ('pendukung', '1.d Dokumen Pendukung'), ('undangan', 'Undangan/Surat Permohonan dari Penyelenggara'), ('kak', 'Kerangka Acuan Kerja (KAK)'), ('rab', 'RAB Pembiayaan'), ('itinerary', 'Jadwal Kegiatan/Itinerary'), ('loa', 'Letter of Acceptance (LoA)'), ('log', 'Letter of Guarantee (LoG)'), ('surat_pernyataan', 'Surat Pernyataan sesuai ketentuan Kemensetneg'), ('drh', 'Daftar Riwayat Hidup (DRH)'), ('ikatan_dinas', 'Perjanjian Ikatan Dinas')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dokumenunor',
            name='jenis',
            field=models.CharField(choices=[('disposisi', '2.a Lembar Disposisi / Izin Prinsip'), ('iln_pimpinan', '2.b Formulir Izin Luar Negeri (TTD Pimpinan Unor)'), ('nd_biropakln', '2.c Nota Dinas Sekertaris Unor ke Biro PAKLN'), ('izin_prinsip', 'Izin Prinsip Menteri'), ('surat_tugas', 'Surat Tugas'), ('nd_kabiro_pakln', 'Nota Dinas Sekretaris Unor ke Kepala Biro PAKLN'), ('nd_sek_bpsdm', 'Nota Dinas Sekretaris Unor ke Sekretaris BPSDM'), ('drh_ttd', 'DRH ttd Pimpinan Unor')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pengajuan',
            name='status',
            field=models.CharField(choices=[('belum', 'Belum Diajukan'), ('proses', 'Dalam Proses Unor'), ('proses_bpsdm', 'Dalam Proses BPSDM'), ('proses_pakln', 'Dalam Proses Biro PAKLN'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='belum', max_length=20),
        ),
        migrations.AlterField(
            model_name='riwayatpengajuan',
            name='aksi',
            field=models.CharField(choices=[('dikirim', 'Diajukan ke Admin Unor'), ('dikirim_ulang', 'Perbaikan dikirim ke Admin Unor'), ('dikembalikan_unor', 'Dikembalikan Admin Unor ke Pegawai'), ('diteruskan_pakln', 'Diteruskan ke Biro PAKLN'), ('dikembalikan_pakln', 'Dikembalikan Biro PAKLN ke Admin Unor'), ('diteruskan_ulang', 'Perbaikan diteruskan ke Biro PAKLN'), ('selesai', 'Selesai diproses'), ('diteruskan_bpsdm', 'Diteruskan ke Admin BPSDM'), ('diteruskan_ulang_bpsdm', 'Perbaikan diteruskan ke Admin BPSDM'), ('dikembalikan_bpsdm', 'Dikembalikan BPSDM ke Admin Unor'), ('laporan_diunggah', 'Laporan PDLN diunggah'), ('laporan_dikembalikan', 'Laporan PDLN dikembalikan'), ('laporan_disetujui', 'Laporan PDLN disetujui'), ('pembatalan_diajukan', 'Permohonan pembatalan diajukan'), ('pembatalan_ditarik', 'Permohonan pembatalan ditarik'), ('pembatalan_disetujui_unor', 'Pembatalan disetujui Admin Unor'), ('pembatalan_ditolak_unor', 'Pembatalan ditolak Admin Unor'), ('pembatalan_ditolak_pakln', 'Pembatalan ditolak Biro PAKLN'), ('dibatalkan', 'Perjalanan dibatalkan')], max_length=30),
        ),
        migrations.AlterField(
            model_name='riwayatpengajuan',
            name='status_dari',
            field=models.CharField(choices=[('belum', 'Belum Diajukan'), ('proses', 'Dalam Proses Unor'), ('proses_bpsdm', 'Dalam Proses BPSDM'), ('proses_pakln', 'Dalam Proses Biro PAKLN'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riwayatpengajuan',
            name='status_ke',
            field=models.CharField(choices=[('belum', 'Belum Diajukan'), ('proses', 'Dalam Proses Unor'), ('proses_bpsdm', 'Dalam Proses BPSDM'), ('proses_pakln', 'Dalam Proses Biro PAKLN'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='pengajuan',
            index=models.Index(fields=['jenis_perjalanan', 'tipe_pdln', 'status'], name='pengajuan_p_jenis_p_ef2cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='pengajuan',
            index=models.Index(fields=['unit_organisasi', 'status'], name='pengajuan_p_unit_or_1d89d9_idx'),
        ),
        migrations.AddIndex(
            model_name='pengajuan',
            index=models.Index(fields=['status', 'tgl_pengajuan'], name='pengajuan_p_status_795718_idx'),
        ),
        migrations.AddIndex(
            model_name='pengajuan',
            index=models.Index(fields=['pegawai', 'status'], name='pengajuan_p_pegawai_9b489c_idx'),
        ),
        migrations.AddField(
            model_name='detailpdln',
            name='pengajuan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pdln', to='pengajuan.pengajuan'),
        ),
        migrations.AddField(
            model_name='dokumenbpsdm',
            name='pengajuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_bpsdm', to='pengajuan.pengajuan'),
        ),
        migrations.AddField(
            model_name='laporanpdln',
            name='diunggah_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporanpdln',
            name='diverifikasi_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laporanpdln',
            name='pengajuan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_pdln', to='pengajuan.pengajuan'),
        ),
        migrations.AddField(
            model_name='permohonanpembatalan',
            name='diajukan_oleh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permohonanpembatalan',
            name='pakln_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permohonanpembatalan',
            name='pengajuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permohonan_pembatalan', to='pengajuan.pengajuan'),
        ),
        migrations.AddField(
            model_name='permohonanpembatalan',
            name='unor_oleh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='dokumenbpsdm',
            unique_together={('pengajuan', 'jenis')},
        ),
        migrations.AddIndex(
            model_name='permohonanpembatalan',
            index=models.Index(fields=['pengajuan', 'status'], name='pengajuan_p_pengaju_064691_idx'),
        ),
    ]
