# Generated by Django 6.1.1 on 2026-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nama Berkas')),
                ('object_name', models.CharField(max_length=255, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Ukuran (byte)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Berkas Terunggah',
                'verbose_name_plural': 'Berkas Terunggah',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
