# Generated by Django 6.1.1 on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models

# Data awal tabel org_units — unit organisasi eselon I Kementerian PU.
ORG_UNITS = [
    ("00", "MENTERI", "Menteri Pekerjaan Umum"),
    ("01", "SETJEN", "Sekretariat Jenderal"),
    ("02", "ITJEN", "Inspektorat Jenderal"),
    ("03", "DJSDA", "Direktorat Jenderal Sumber Daya Air"),
    ("04", "DJPS", "Direktorat Jenderal Prasarana Strategis"),
    ("05", "DJCK", "Direktorat Jenderal Cipta Karya"),
    ("06", "DJBM", "Direktorat Jenderal Bina Marga"),
    ("07", "DJPI", "Direktorat Jenderal Pembiayaan Infrastruktur"),
    ("08", "DJBK", "Direktorat Jenderal Bina Konstruksi"),
    ("09", "BPIW", "Badan Pengembangan Infrastruktur Wilayah"),
    ("10", "BPSDM", "Badan Pengembangan Sumber Daya Manusia"),
]

# Pemetaan nilai teks lama (bebas) ke alias unit organisasi.
LEGACY_ALIAS = {
    "ditjen sumber daya air": "DJSDA",
    "ditjen bina marga": "DJBM",
    "ditjen cipta karya": "DJCK",
    "ditjen prasarana strategis": "DJPS",
    "ditjen pembiayaan infrastruktur": "DJPI",
    "ditjen bina konstruksi": "DJBK",
    "sekretariat jenderal": "SETJEN",
    "inspektorat jenderal": "ITJEN",
}

# Tangkapan sementara nilai lama (pk model -> pk UnitOrganisasi) agar dapat
# dipulihkan setelah kolom diganti menjadi ForeignKey.
_CAPTURED = {}


def _resolve(Unit, text):
    if not text:
        return None
    t = str(text).strip().lower()
    for u in Unit.objects.all():
        if t in (u.name.lower(), u.alias.lower()):
            return u
    if t in LEGACY_ALIAS:
        return Unit.objects.filter(alias=LEGACY_ALIAS[t]).first()
    for u in Unit.objects.all():
        if u.alias.lower() in t or t in u.name.lower():
            return u
    return None


def seed_units(apps, schema_editor):
    Unit = apps.get_model("accounts", "UnitOrganisasi")
    for code, alias, name in ORG_UNITS:
        Unit.objects.update_or_create(code=code, defaults={"alias": alias, "name": name})


def unseed_units(apps, schema_editor):
    apps.get_model("accounts", "UnitOrganisasi").objects.all().delete()


def capture_old(apps, schema_editor):
    Unit = apps.get_model("accounts", "UnitOrganisasi")
    _CAPTURED.clear()
    for model_name in ("User", "PegawaiProfile"):
        Model = apps.get_model("accounts", model_name)
        for obj in Model.objects.all():
            unit = _resolve(Unit, getattr(obj, "unit_organisasi", None))
            if unit:
                _CAPTURED[(model_name, obj.pk)] = unit.pk


def restore_new(apps, schema_editor):
    for (model_name, pk), unit_pk in _CAPTURED.items():
        Model = apps.get_model("accounts", model_name)
        Model.objects.filter(pk=pk).update(unit_organisasi_id=unit_pk)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_unit_organisasi"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOrganisasi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=2, unique=True, verbose_name="Kode")),
                ("alias", models.CharField(max_length=20, verbose_name="Alias")),
                ("name", models.CharField(max_length=150, verbose_name="Nama")),
            ],
            options={
                "verbose_name": "Unit Organisasi",
                "verbose_name_plural": "Unit Organisasi",
                "db_table": "org_units",
                "ordering": ["code"],
            },
        ),
        migrations.RunPython(seed_units, unseed_units),
        migrations.RunPython(capture_old, noop),
        migrations.RemoveField(model_name="user", name="unit_organisasi"),
        migrations.RemoveField(model_name="pegawaiprofile", name="unit_organisasi"),
        migrations.AddField(
            model_name="user",
            name="unit_organisasi",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name="+", to="accounts.unitorganisasi", verbose_name="Unit Organisasi",
            ),
        ),
        migrations.AddField(
            model_name="pegawaiprofile",
            name="unit_organisasi",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                related_name="+", to="accounts.unitorganisasi", verbose_name="Unit Organisasi",
            ),
        ),
        migrations.RunPython(restore_new, noop),
    ]
