# Generated by Django 6.1.1 on 2026-09-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_unit_organisasi_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unit_kerja',
            field=models.CharField(blank=True, max_length=150, verbose_name='Unit Kerja'),
        ),
    ]
