# Generated by Django 6.1.1 on 2026-10-05 06:32

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_move_unitorganisasi_to_paspor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pegawai', 'Pegawai'), ('admin_unor', 'Admin Unor'), ('admin_bpsdm', 'Admin BPSDM'), ('admin_pakln', 'Admin Biro PAKLN')], max_length=20),
        ),
        migrations.CreateModel(
            name='PasporPegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=20, verbose_name='Nomor Paspor')),
                ('jenis', models.CharField(choices=[('biasa', 'Paspor Biasa'), ('dinas', 'Paspor Dinas'), ('diplomatik', 'Paspor Diplomatik')], default='biasa', max_length=20, verbose_name='Jenis Paspor')),
                ('tgl_expired', models.DateField(verbose_name='Tanggal Expired')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paspor_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paspor Pegawai',
                'verbose_name_plural': 'Paspor Pegawai',
                'ordering': ['-tgl_expired'],
            },
        ),
        migrations.CreateModel(
            name='DokumenKepegawaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('ktp', 'KTP'), ('kk', 'Kartu Keluarga'), ('kartu_pegawai', 'Kartu Pegawai/SK Pengangkatan PNS'), ('ijazah', 'Akta Kelahiran/Ijazah Terakhir'), ('sk_pangkat', 'SK Kenaikan Pangkat Terakhir'), ('pas_foto', 'Pas Foto (4x6 latar putih)'), ('sk_penugasan', 'SK Penugasan Admin')], max_length=20)),
                ('file', models.FileField(upload_to=accounts.models.dokumen_kepegawaian_path)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen_kepegawaian', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dokumen Kepegawaian',
                'verbose_name_plural': 'Dokumen Kepegawaian',
                'unique_together': {('user', 'jenis')},
            },
        ),
    ]
