# Generated by Django 6.1.1 on 2026-10-08 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=30)),
                ('aktivitas', models.CharField(max_length=50)),
                ('deskripsi', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('success', 'Berhasil'), ('failed', 'Gagal')], default='success', max_length=10)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_method', models.CharField(blank=True, max_length=10)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='log_timestamp_idx'), models.Index(fields=['aktivitas', 'timestamp'], name='log_aktivitas_ts_idx'), models.Index(fields=['status', 'timestamp'], name='log_status_ts_idx'), models.Index(fields=['user', 'timestamp'], name='log_user_ts_idx')],
            },
        ),
    ]
