# Generated by Django 6.1.1 on 2026-09-30 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paspor', '0004_kategoriperjalanan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HariLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True, verbose_name='Tanggal')),
                ('keterangan', models.CharField(max_length=150, verbose_name='Keterangan')),
                ('jenis', models.CharField(choices=[('libur_nasional', 'Libur Nasional'), ('cuti_bersama', 'Cuti Bersama')], default='libur_nasional', max_length=20, verbose_name='Jenis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hari Libur',
                'verbose_name_plural': 'Hari Libur',
                'ordering': ['tanggal'],
            },
        ),
    ]
