# Generated by Django 6.1.1 on 2026-10-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paspor', '0005_harilibur'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriperjalanan',
            name='tipe_pdln',
            field=models.JSONField(blank=True, default=list, verbose_name='Berlaku untuk Tipe PDLN'),
        ),
        migrations.AddField(
            model_name='negara',
            name='perlu_visa',
            field=models.BooleanField(default=False, help_text='Centang bila perjalanan dinas ke negara ini memerlukan visa — Rekomendasi Visa menjadi dokumen wajib pada PDLN.', verbose_name='Memerlukan Visa'),
        ),
        migrations.AddField(
            model_name='sumberpembiayaan',
            name='tipe_pdln',
            field=models.JSONField(blank=True, default=list, verbose_name='Berlaku untuk Tipe PDLN'),
        ),
    ]
