# Generated by Django 6.1.1 on 2026-09-22 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pengajuan', '0005_dokumenunorpendukung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('NOTIF_01_SUBMIT_UNOR', 'Pengajuan Surat Baru'), ('NOTIF_02A_APPROVE_UNOR', 'Disetujui Unor / Diteruskan ke PKLN'), ('NOTIF_02B_REJECT_UNOR', 'Dikembalikan oleh Admin Unor'), ('NOTIF_02C_RESUBMIT_UNOR', 'Pengajuan Ulang ke Admin Unor'), ('NOTIF_03A_COMPLETE_PKLN', 'Selesai & Terbit oleh Admin PKLN')], max_length=40)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='info', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('redirect_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_toasted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pengajuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='pengajuan.pengajuan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notifikasi',
                'verbose_name_plural': 'Notifikasi',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'is_toasted'], name='notificatio_recipie_f8beac_idx')],
            },
        ),
    ]
