# Generated by Django 6.1.1 on 2026-09-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_is_dismissed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('NOTIF_01_SUBMIT_UNOR', 'Pengajuan Surat Baru'), ('NOTIF_02A_APPROVE_UNOR', 'Disetujui Unor / Diteruskan ke PKLN'), ('NOTIF_02B_REJECT_UNOR', 'Dikembalikan oleh Admin Unor'), ('NOTIF_02C_RESUBMIT_UNOR', 'Pengajuan Ulang ke Admin Unor'), ('NOTIF_03A_COMPLETE_PKLN', 'Selesai & Terbit oleh Admin PKLN'), ('NOTIF_03B_REJECT_PKLN_TO_UNOR', 'Dikembalikan Admin PKLN ke Admin Unor')], max_length=40),
        ),
    ]
