# Generated by Django 6.1.1 on 2026-10-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('NOTIF_01_SUBMIT_UNOR', 'Pengajuan Surat Baru'), ('NOTIF_02A_APPROVE_UNOR', 'Disetujui Unor / Diteruskan ke PKLN'), ('NOTIF_02B_REJECT_UNOR', 'Dikembalikan oleh Admin Unor'), ('NOTIF_02C_RESUBMIT_UNOR', 'Pengajuan Ulang ke Admin Unor'), ('NOTIF_03A_COMPLETE_PKLN', 'Selesai & Terbit oleh Admin PKLN'), ('NOTIF_03B_REJECT_PKLN_TO_UNOR', 'Dikembalikan Admin PKLN ke Admin Unor'), ('NOTIF_04A_FORWARD_BPSDM', 'Diteruskan Unor ke Admin BPSDM'), ('NOTIF_04B_RESUBMIT_BPSDM', 'Perbaikan diteruskan ke Admin BPSDM'), ('NOTIF_04C_REJECT_BPSDM_TO_UNOR', 'Dikembalikan Admin BPSDM ke Admin Unor'), ('NOTIF_05A_LAPORAN_DIUNGGAH', 'Laporan PDLN diunggah'), ('NOTIF_05B_LAPORAN_DIKEMBALIKAN', 'Laporan PDLN dikembalikan'), ('NOTIF_05C_LAPORAN_DISETUJUI', 'Laporan PDLN disetujui'), ('NOTIF_06A_PEMBATALAN_DIAJUKAN', 'Permohonan pembatalan diajukan'), ('NOTIF_06B_PEMBATALAN_MENUNGGU_PAKLN', 'Pembatalan menunggu Biro PAKLN'), ('NOTIF_06C_PEMBATALAN_DITOLAK', 'Permohonan pembatalan ditolak'), ('NOTIF_06D_PEMBATALAN_DISETUJUI', 'Perjalanan dibatalkan'), ('NOTIF_06E_PEMBATALAN_DITARIK', 'Permohonan pembatalan ditarik')], max_length=40),
        ),
    ]
