# Generated by Django 6.1.1 on 2026-10-09 06:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_event'),
        ('pengajuan', '0019_backfill_unit_organisasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(blank=True, max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=150)),
                ('event', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=255)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('sending', 'Dikirim'), ('sent', 'Terkirim'), ('failed', 'Gagal'), ('skipped', 'Dilewati')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, max_length=100)),
                ('last_error', models.TextField(blank=True)),
                ('status_note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pengajuan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='pengajuan.pengajuan')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Email',
                'verbose_name_plural': 'Log Email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='emaillog_status_next_idx'), models.Index(fields=['created_at'], name='emaillog_created_idx')],
            },
        ),
    ]
